from shiftmanager import TableDefinitionStatement, connect_from_env

conn = connect_from_env()
next_migration_index = 60

def migrate(tablename, **kwargs):
    global next_migration_index
    filename = ("V{:0>4}__alter_keys_for_{}.sql"
                .format(next_migration_index, tablename))
    tds = TableDefinitionStatement(conn, tablename, **kwargs)
    next_migration_index += 1
    with open(filename, 'w') as f:
        f.write("-- Generated by a script from "
                "https://github.banksimple.com/analytics/shiftmanager/"
                "\n\n")
        f.write(tds.definition())
        f.write('\n')
    print("Wrote " + filename)

# Add dist keys and sort keys to coinscope tables
migrate('user_event', distkey='user_id', sortkey='when_created')
migrate('invitation', distkey='user_id', sortkey='when_created')
migrate('transaction', distkey='user_id', sortkey='when_received')
migrate('transaction_kv', distkey='user_id', sortkey='when_received')

# Change flapjack_redirect_events to a compound sortkey
migrate('flapjack_redirect_events', sortkey='name, when_recorded')

## Add browser_cookie as the dist key for several flapjack tables where user_id not available
migrate('flapjack_flapjack', distkey='browser_cookie')
migrate('flapjack_misc', distkey='browser_cookie')
migrate('flapjack_mobile_without_user', distkey='browser_cookie')
migrate('flapjack_web_without_user', distkey='browser_cookie')

## Add some missing sort keys
migrate('segmentio_android', sortkey='when_recorded')
migrate('segmentio_ios', sortkey='when_recorded')

## Replicate some small, mostly static tables to all nodes
migrate('data_make_good_customers', diststyle='ALL')
migrate('flapjack_redirect', diststyle='ALL')
migrate('flapjack_csp', diststyle='ALL')
migrate('sawtooth_mabel_agent_data', diststyle='ALL')
migrate('sawtooth_belvedere_hashtags', diststyle='ALL')
