from shiftmanager import TableDefinitionStatement as TDS, connect_from_env

conn = connect_from_env()

tableDefinitions = [

    # Add dist keys and sort keys to coinscope tables
    TDS(conn, 'user_event', distkey='user_id', sortkey='when_created', owner='importer'),
    TDS(conn, 'invitation', distkey='user_id', sortkey='when_created', owner='importer'),
    TDS(conn, 'transaction', distkey='user_id', sortkey='when_received', owner='importer'),
    TDS(conn, 'transaction_kv', distkey='user_id', sortkey='when_received', owner='importer'),

    # Change flapjack_redirect_events to a compound sortkey
    TDS(conn, 'flapjack_redirect_events', sortkey='name, when_created'),

    ## Add browser_cookie as the dist key for several flapjack tables where user_id not available
    TDS(conn, 'flapjack_flapjack', distkey='browser_cookie'),
    TDS(conn, 'flapjack_misc', distkey='browser_cookie'),
    TDS(conn, 'flapjack_mobile_without_user', distkey='browser_cookie'),
    TDS(conn, 'flapjack_web_without_user', distkey='browser_cookie'),

    ## Add some missing sort keys
    TDS(conn, 'segmentio_android', sortkey='when_recorded'),
    TDS(conn, 'segmentio_ios', sortkey='when_recorded'),

    ## Replicate some small, mostly static tables to all nodes
    TDS(conn, 'data_make_good_customers', distkey='ALL'),
    TDS(conn, 'flapjack_redirect', distkey='ALL'),
    TDS(conn, 'flapjack_csp', distkey='ALL'),
    TDS(conn, 'sawtooth_mabel_agent_data', distkey='ALL'),
    TDS(conn, 'sawtooth_belvedere_hashtags', distkey='ALL'),

]

with open('V0058__reconfigure_sort_and_dist_keys.sql', 'w') as f:
    f.write("-- Generated by a script from "
            "https://github.banksimple.com/analytics/shiftmanager/"
            "\n\n")
    for t in tableDefinitions:
        f.write(t.definition())
        f.write('\n\n\n')
    f.write("DROP TABLE IF EXISTS old_segmentio_android;\n")
